data_aligner:
  _target_: src.dd.align.data_aligner.DataAlignerV2
  chunk_size: &chunk_size 1024
#  segmenter:
#    _target_: src.dd.align.segmenter.FixedSizeSegmenter
#    segment_size: 2097152
  segmenter:
    _target_: src.dd.align.segmenter.VariableSizeSegmenter
    chunk_size: *chunk_size
    rolling_hash:
      q: 1000000007
      x: 7
    segment_size: 1048576


captain_hook:
  _target_: src.dd.sparse_index.CaptainHook
  hook_prefix_len: 4


